version: "3"

tasks:
  setup:
    desc: setup all requirements
    silent: true
    cmds:
      - |
        if ! dpkg -s nvidia-container-toolkit >/dev/null 2>&1; then
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
          | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg   && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
          | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
          | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
          sudo apt-get install -y nvidia-container-toolkit nvidia-docker2
          # cgroupfs-mount
        fi

  up:*:
    desc: "up docker compose (use: task up:[cpu|nvidia|amd|intel])"
    silent: true
    vars:
      profile: "{{index .MATCH 0}}"
    cmds:
      - |
        case "{{.profile}}" in
          cpu|nvidia|amd|intel) ;;
          *)
            echo "Error: profile is not one of cpu, nvidia, amd, intel"
            exit 1
            ;;
        esac
      - docker compose --profile {{.profile}} up

  build:
    desc: build docker compose
    silent: true
    cmds:
      - docker compose --profile nvidia build
      - docker compose --profile amd build
      - docker compose --profile intel build

  push:
    desc: build and push docker compose
    silent: true
    deps:
      - build
    cmds:
      - docker push ghcr.io/devil666face/ollama:nvidia
      - docker push ghcr.io/devil666face/ollama:amd
      - docker push ghcr.io/devil666face/ollama:intel
      - docker save ghcr.io/devil666face/ollama:nvidia | gzip > ollama_nvidia.tar.gz
      - docker save ghcr.io/devil666face/ollama:amd | gzip > ollama_amd.tar.gz
      - docker save ghcr.io/devil666face/ollama:intel | gzip > ollama_intel.tar.gz

  prune:
    desc: remove containers
    silent: true
    cmds:
      - docker rm --force ollama postgres n8n open-webui traefik proxy
      - sudo rm -rf data
