FROM ollama/ollama:rocm

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    TZ=UTC \
    PATH="/root/.local/bin:/root/.venv/bin:${PATH}"

WORKDIR /root

RUN apt-get update --quiet --quiet && \
    apt-get install --quiet --quiet --yes \
    curl \
    && apt-get --quiet --quiet clean \
    && rm --recursive --force /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

COPY pyproject.toml .
COPY uv.lock .
COPY .python-version .

ADD https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz /tmp/gotty_linux_amd64.tar.gz
RUN tar -xf /tmp/gotty_linux_amd64.tar.gz && \
    chmod +x gotty && \
    mv gotty /usr/local/bin && \
    rm /tmp/gotty_linux_amd64.tar.gz

RUN uv sync
# RUN uv sync --extra unsloth

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
