FROM ollama/ollama:latest

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    TZ=UTC \
    PATH="/root/.local/bin:/.venv/bin:${PATH}"

RUN apt-get update --quiet --quiet && \
    apt-get install --quiet --quiet --yes \
    curl \
    && apt-get --quiet --quiet clean \
    && rm --recursive --force /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

COPY pyproject.toml .
COPY uv.lock .
COPY .python-version .

RUN uv sync

COPY entrypoint.sh .

ENTRYPOINT ["/entrypoint.sh"]
